resilience4j.retry:
    instances:
        mentor:
            registerHealthIndicator: true
            maxAttempts: 1
            waitDuration: 10s


resilience4j.circuitbreaker:
  instances:
    mentor:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      failureRateThreshold: 70
      #minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2000
      automaticTransitionFromOpenToHalfOpenEnabled: true
      
resilience4j.ratelimiter:
  instances:
    mentor:
      limitRefreshPeriod: 24s
      limitForPeriod: 5
      timeoutDuration: 20s
      registerHealthIndicator: true


management:
  endpoint:
    health:
      show-details: always         #To show all details in /health endpoint.

management.health.circuitbreakers.enabled: true